name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Security Scan
        run: snyk test --severity-threshold=high || true  # Prevents pipeline failure

  zap_scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-22.04
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove Cached GitHub Actions
        run: rm -rf ${{ runner.tool_cache }}/actions

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Pull ZAP Docker Image
        run: docker pull owasp/zap2docker-stable

      - name: Run ZAP Baseline Scan with Debug Mode
        run: |
          docker run --rm -v $(pwd):/zap/wrk owasp/zap2docker-stable zap-baseline.py \
            -t https://your-app-url.com -r zap_report.html --debug

      - name: Wait before uploading artifact
        run: sleep 5s

      - name: Verify ZAP Report Exists
        run: ls -lh zap_report.html || echo "⚠️ ZAP report not found!"

      - name: Upload ZAP Report (Final Fix)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Security Report
          path: zap_report.html
          repository: actions/upload-artifact

