name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-20.04  # ✅ Stable runner version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  zap_scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-20.04  # ✅ Ensuring compatibility
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Manually Fetch Required Actions  # ✅ Forces GitHub to fetch required actions
        run: |
          gh extension install actions/checkout
          gh extension install actions/upload-artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove Cached GitHub Actions
        run: rm -rf ${{ runner.tool_cache }}/actions

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Pull ZAP Docker Image
        run: docker pull owasp/zap2docker-stable

      - name: Run ZAP Baseline Scan with Debug Mode
        run: |
          docker run --rm -v $(pwd):/zap/wrk owasp/zap2docker-stable zap-baseline.py \
            -t https://your-app-url.com -r zap_report.html --debug

      - name: Wait before uploading artifact
        run: sleep 5s

      - name: Verify ZAP Report Exists
        run: ls -lh zap_report.html || echo "⚠️ ZAP report not found!"

      - name: Upload ZAP Report  # ✅ FIXED: Now using v3
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Security Report
          path: zap_report.html
